FROM centos:centos7

MAINTAINER kobarasukimaro

#RUN groupadd -r centos && useradd -r -g centos centos
RUN yum update
RUN yum -y groupinstall "Development Tools"

RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -
RUN yum -y install nodejs
RUN npm install -g terminalizer --unsafe
